### - Testy rejestracji - 

### Test statusu serwera
GET http://localhost:3000/

### Rejestracja nowego użytkownika
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "Gracz2",
    "password": "TajneHaslo123"
}

### Logowanie z powyższymi danymi
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "Gracz2",
    "password": "TajneHaslo123"
}

### Wylogowanie
POST http://localhost:3000/api/auth/logout

### Sprawdzamy czy sesja działa
GET http://localhost:3000/api/auth/me