### Test statusu serwera
GET http://localhost:3000/

### Wylogowanie
POST http://localhost:3000/auth/logout

### Sprawdzamy czy sesja działa
GET http://localhost:3000/auth/me

### Tworzenie pokoju
POST http://localhost:3000/rooms
Content-Type: application/json

{
    "difficulty": "medium"
}
### Pobieramy liste pokoji
GET http://localhost:3000/rooms

### Pobranie historii czatu
GET http://localhost:3000/chat/history

### Dodaj wiadomość do czatu
POST http://localhost:3000/chat
Content-Type: application/json

{
    "message": "Cześć! To test API."
}
